services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dinsas-app
    container_name: dinsas-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - dinsas-network
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: dinsas-nginx
    restart: unless-stopped
    ports:
      - "6091:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - dinsas-network
    depends_on:
      - app

  db:
    image: mariadb:10.11
    container_name: dinsas-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - dinsas-network
    ports:
      - "33066:3306"

networks:
  dinsas-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
